name: legend_mfast
description: Legend MFast Website
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  bloc: 8.1.2
  auto_route: 7.8.3
  get_it: 7.6.4
  dio: 5.3.2
  intl: 0.18.1
  formz: 0.6.0
  equatable: 2.0.5

  firebase_core: 2.12.0
  firebase_core_web: 2.5.0
  firebase_auth: 4.6.0
  firebase_database: 10.2.0

  event_bus: 2.0.0
  dotted_border: 2.0.0+3
  dotted_decoration: 2.0.0
  dotted_line: 3.2.2
  graphql_flutter: 5.2.0-beta.5
  fresh_graphql: 0.6.0
  popover: 0.2.8+2
  url_launcher: 6.1.14
  collection: 1.17.2
  url_strategy: 0.2.0
  photo_manager: 2.7.1
  emojis: 0.9.9
  string_validator: 1.0.0
  jwt_decode: 0.3.1
  universal_html: 2.2.4
  transparent_image: 2.0.1
  flutter_portal: 1.1.4
  pull_to_refresh: 2.0.0
  flutter_image_compress: 2.0.4
  just_audio: 0.9.34
  #  audio_waveforms: 1.0.4
  path_provider: 2.1.1
  fluttertoast: 8.2.2
  cached_network_image: 3.2.3
  flutter_html: 3.0.0-alpha.6
  share_plus: 7.1.0
  flutter_sticky_header: 0.6.5
  image_picker: 1.0.4
  app_settings: 5.0.0
  flutter_switch: 0.3.2
  video_player: 2.7.0
  slivers: 0.0.1+2
  scroll_to_index: 3.0.1
  photo_view: 0.14.0
  gallery_saver: 2.3.2
  flutter_xlider: 3.5.0
  flutter_sound: 9.2.13
  image_size_getter: 2.1.2
  ezanimation: 0.6.0
  lottie: 2.7.0
  flutter_json_path: 0.0.5
  flutter_audio_waveforms: 1.2.1+8
  assorted_layout_widgets: 8.0.4
  any_link_preview: 3.0.1
  flutter_linkify: 6.0.0
  flutter_parsed_text: 2.2.1
  screenshot: 2.1.0
  google_maps_flutter: 2.5.0
  geolocator: 10.0.1
  permission_handler: 11.0.1
  mime: 1.0.4
  get_thumbnail_video: 0.6.1
  image_downloader_web: 2.0.4
  percent_indicator: 4.2.3
  extended_nested_scroll_view: 6.1.2
  liquid_pull_to_refresh: 3.0.1
  loading_more_list: 5.0.3
  hive: 2.2.3
  uuid: 3.0.7
  flutter_staggered_grid_view: 0.7.0
  info_popup: 4.3.1
  flutter_rating_bar: 4.0.1
  page_transition: 2.1.0
  pretty_qr_code: 3.0.0
  convex_bottom_bar: 3.2.0

dependency_overrides:
  http: 1.1.0
  flutter_layout_grid: 2.0.5

dev_dependencies:
  flutter_lints: 2.0.3
  auto_route_generator: 7.3.1
  build_runner: 2.4.6
  hive_generator: 2.0.1
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/

  fonts:
    - family: MFastVN
      fonts:
        - asset: assets/fonts/MFastVN-Light.ttf
          weight: 300
        - asset: assets/fonts/MFastVN-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/MFastVN-Regular.ttf
          weight: 400
        - asset: assets/fonts/MFastVN-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/MFastVN-Medium.ttf
          weight: 500
        - asset: assets/fonts/MFastVN-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/MFastVN-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MFastVN-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/MFastVN-Bold.ttf
          weight: 700
        - asset: assets/fonts/MFastVN-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/MFastVN-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MFastVN-ExtraBoldItalic.ttf
          weight: 800
          style: italic
